import string
import re
import difflib
import textwrap
import unicodedata
import stringprep
import readline
import rlcompleter
import struct
import codecs
import datetime
import zoneinfo
import calendar
import collections
import collections.abc
import heapq
import bisect
import array
import weakref
import types
import copy
import pprint
import reprlib
import enum
import graphlib
import numbers
import cmath
import math
import decimal
import fractions
import random
import statistics
import itertools
import functools
import operator
import pathlib
import os.path
import fileinput
import stat
import filecmp
import tempfile
import glob
import fnmatch
import linecache
import shutil
import pickle
import copyreg
import shelve
import marshal
import dbm
import sqlite3
import zlib
import gzip
import bz2
import lzma
import zipfile
import tarfile
import csv
import configparser
import netrc
import plistlib
import hashlib
import hmac
import secrets
import os
import io
import time
import argparse
import getopt
import logging
import logging.config
import logging.handlers
import getpass
import curses
import curses.textpad
import curses.ascii
import curses.panel
import platform
import errno
import ctypes

print('hello world')
